Added the contribution Guidelines
aliraza944/school-time-table-management pull request #7
Opened 2022-06-21 17:35 UTC by Amisha0606

This is an incomplete contribution file. I will keep updating it in future.

2022-06-21 18:22 UTC, aliraza944 requested changes

2022-06-21 18:22 UTC, aliraza944 commented on CONTRIBUTING.md
> +   git add .
I think it should be  `git add <files you have changed>` instead of the `git add .` . Because once we have set up the GitHub CI/CD  if any contributor uses `git add  .` then they will commit their package.json and package.lock.json among other configs that work only on their system. This will cause our project dependencies to change with every commit.

2022-06-21 18:22 UTC, aliraza944 commented on CONTRIBUTING.md
> +   git init
This is not necessary because git will be already initialized once you have cloned the repo.

2022-06-21 18:23 UTC, aliraza944 commented
@Amisha0606 great job. Just commit these changes I have requested and I will merge in no time.

2022-06-22 17:59 UTC, Amisha0606 commented on CONTRIBUTING.md
> +   git add .
Yupp. Makes sense.

2022-06-22 18:22 UTC, aliraza944 approved these changes
That's great...

2022-06-22 18:23 UTC, merged